### ISSUE TITLE
Bugs in Attention benchmark

### ISSUE THREAD

**Issue by hypnopump** [kakaobrain/trident#162]
## 🐞 Describe the bug

Running the` benchmarks/bechmarker.py` yields an error in the attention scenario. 

## 🧑‍🏫 Reproduction

Just install latest version following instructions from https://github.com/kakaobrain/trident/issues/159#issuecomment-1750862031 and run: 

```bash
(python310) root@mymachine-17037-1045294:~/trident/benchmarks# CUDA_LAUNCH_BLOCKING=1 python benchmarker.py --scenario attention
Traceback (most recent call last):
  File "/root/trident/benchmarks/benchmarker.py", line 191, in <module>
    main()
  File "/root/trident/benchmarks/benchmarker.py", line 182, in main
    run_benchmarks(
  File "/root/trident/benchmarks/benchmarker.py", line 83, in run_benchmarks
    benchmark_attention.run_benchmark(mode, show_plots, dtype)
  File "/root/trident/benchmarks/benchmark_attention.py", line 62, in run_benchmark
    bench_attention_forward.run(print_data=True, show_plots=show_plots, dtype=dtype)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/testing.py", line 337, in run
    self._run(bench, save_path, show_plots, print_data, **kwargs)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/testing.py", line 289, in _run
    ret = self.fn(**x_args, **{bench.line_arg: y}, **bench.args, **kwrags)
  File "/root/trident/benchmarks/benchmark_attention.py", line 34, in bench_attention_forward
    return triton.testing.do_bench(
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/testing.py", line 105, in do_bench
    fn()
  File "/root/trident/benchmarks/benchmark_attention.py", line 35, in <lambda>
    lambda: trident.function.scaled_dot_product_attention(query, key, value, use_accelerator=True)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/trident/function/function.py", line 251, in scaled_dot_product_attention
    return operation.Attention.apply(
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/trident/operation/attention.py", line 38, in forward
    output, log_sum_exp = Attention.__forward(
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/trident/operation/attention.py", line 99, in __forward
    kernel.Attention.forward[grid](
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 104, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 104, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 87, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/testing.py", line 105, in do_bench
    fn()
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages,
  File "<string>", line 4, in forward
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/triton/runtime/jit.py", line 410, in launcher_body
    bin.c_wrapper(grid_0, grid_1, grid_2, bin.num_warps, bin.num_ctas, bin.clusterDims[0], bin.clusterDims[1], bin.clusterDims[2], bin.shared, stream, bin.cu_function, CompiledKernel.launch_enter_hook, CompiledKernel.launch_exit_hook, bin, *args)
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

## 🎯 Expected behavior

Ideally it should just give the running times as in the `argmax` case: 

```bash
(python310) root@mymachine-17037-1045294:~/trident/benchmarks# python benchmarker.py
argmax forward:
    x_size     torch   trident
0    128.0  0.004781  0.002036
1    256.0  0.005041  0.002055
2    384.0  0.005651  0.002100
3    512.0  0.006145  0.002124
4    640.0  0.006773  0.002186
5    768.0  0.007327  0.002097
6    896.0  0.008035  0.002210
7   1024.0  0.008468  0.002203
8   1152.0  0.009113  0.002335
9   1280.0  0.009662  0.002358
10  1408.0  0.010142  0.002305
11  1536.0  0.010683  0.002369
12  1664.0  0.011376  0.002410
13  1792.0  0.011718  0.002455
14  1920.0  0.012365  0.002451
15  2048.0  0.012884  0.002436
16  2176.0  0.013410  0.002749
17  2304.0  0.013806  0.002733
18  2432.0  0.014543  0.002740
19  2560.0  0.015103  0.002776
```

## 🖼️ Screenshots

.

## 💻 Requirements

- Platform: Ubuntu 20.04.5 LTS
- Hardware: Nvidia V100 32 Gb card. 
- Version: pytorch 2.1, triton-nightly, trident 1.0.2

## 💬 Additional context

Running the function individually in `ipython` worked for a simple case: 
```python
import torch as th
import trident.functional as tdf

q,k,v = th.randn(3, 2, 4, 8, 16).cuda()
tdf.scaled_dot_product_attention(q, k, v, use_accelerator=True)
```

BTW: It would be very helpful if an updated result of running `pytorch bechmarker.py` could be provided in the wiki, so it can be can be seen which functions can be really accelerated (and by which amount) by `trident`

**Comment by daemyung** [comment]
@hypnopump Thanks for your reporting! @ansteve Could you look at this issue?

**Comment by kakao-steve-ai** [comment]
Thanks for the reporting. I will check the issue.

**Comment by ansteve** [comment]
This issue seems to be related to Triton issue https://github.com/openai/triton/issues/1483 .
I found a workaround by using a small block size. Let me prepare the PR.

**Comment by kakao-steve-ai** [comment]
My previous analysis is not correct, so I deleted the comment.
For now, Attention only supports for power of 2 size tensors. That's why tests are passed and the benchmark is failed.

**Comment by hypnopump** [comment]
A woirkaround could be removing non power of 2 tensors from the benchmark in the attention case, or add a padding in the attention function so that kernels don’t fail, and then remove the padding if the original length is not a power of 2. Could that be done?

Eric Alcaide

**Comment by kakao-steve-ai** [comment]
> A woirkaround could be removing non power of 2 tensors from the benchmark in the attention case, or add a padding in the attention function so that kernels don’t fail, and then remove the padding if the original length is not a power of 2. Could that be done? Eric Alcaide

Yes, it is correct. I will update the benchmark not to use non power of 2 tensors.

**Comment by hypnopump** [comment]
Could we implement this in trident?

**Comment by kakao-steve-ai** [comment]
> Could we implement this in trident?

I am not sure it is common to use non power of 2 tensors in Attention. It is not high priority for now.

**Comment by hypnopump** [comment]
in that case, could we modify the attention benchmark to only do powers of
2 so we can have an idea of how fast trident is compared to pure pytorch?

**Comment by kakao-steve-ai** [comment]
```
$ python3 benchmarks/benchmarker.py --scenario attention --mode forward 
attention forward:
   y_size     torch   trident
0    32.0  0.047715  0.315676
1    64.0  0.053139  0.361421
2   128.0  0.127275  0.113559
3   256.0  0.401120  0.239711
4   512.0  1.466141  0.821546
```
@hypnopump  In my environment, the benchmark returns like this.

**Comment by hypnopump** [comment]
HI there, i have tried to run the above code but i'm getting the following error: 
```bash
$ python3 benchmarks/benchmarker.py --scenario attention --mode forward
Traceback (most recent call last):
  File "~/Desktop/projects/trident/benchmarks/benchmarker.py", line 191, in <module>
    main()
  File "~/Desktop/projects/trident/benchmarks/benchmarker.py", line 182, in main
    run_benchmarks(
  File "~/Desktop/projects/trident/benchmarks/benchmarker.py", line 83, in run_benchmarks
    benchmark_attention.run_benchmark(mode, show_plots, dtype)
  File "~/Desktop/projects/trident/benchmarks/benchmark_attention.py", line 62, in run_benchmark
    bench_attention_forward.run(print_data=True, show_plots=show_plots, dtype=dtype)
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/testing.py", line 337, in run
    self._run(bench, save_path, show_plots, print_data, **kwargs)
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/testing.py", line 289, in _run
    ret = self.fn(**x_args, **{bench.line_arg: y}, **bench.args, **kwrags)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Desktop/projects/trident/benchmarks/benchmark_attention.py", line 34, in bench_attention_forward
    return triton.testing.do_bench(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/testing.py", line 105, in do_bench
    fn()
  File "~/Desktop/projects/trident/benchmarks/benchmark_attention.py", line 35, in <lambda>
    lambda: trident.function.scaled_dot_product_attention(query, key, value, use_accelerator=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/trident/function/function.py", line 251, in scaled_dot_product_attention
    return operation.Attention.apply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/trident/operation/attention.py", line 38, in forward
    output, log_sum_exp = Attention.__forward(
                          ^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/trident/operation/attention.py", line 99, in __forward
    kernel.Attention.forward[grid](
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 104, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 104, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 87, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/testing.py", line 105, in do_bench
    fn()
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages,
  File "<string>", line 4, in forward
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/runtime/jit.py", line 428, in launcher_body
    bin = compile(self, signature=signature, device=device, constants=constants, num_warps=num_warps, num_ctas=num_ctas, num_stages=num_stages, enable_warp_specialization=enable_warp_specialization, enable_fp_fusion=enable_fp_fusion, extern_libs=extern_libs, configs=configs, debug=self.debug, device_type=device_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/compiler/compiler.py", line 513, in compile
    next_module = compile_kernel(module)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/compiler/compiler.py", line 412, in <lambda>
    lambda src: ttgir_to_llir(src, extern_libs, target, tma_infos))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/python311/lib/python3.11/site-packages/triton/compiler/compiler.py", line 167, in ttgir_to_llir
    return translate_triton_gpu_to_llvmir(mod, target.capability, tma_infos, runtime.TARGET.NVVM)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: map::at
```
@ansteve @daemyung Is there any environment/config you could share to reproduce?

**Comment by daemyung** [comment]
@hypnopump Sorry for sharing this new. Trident will be not maintained for a while because company have decided dropping this project.
